<?php

class WeddingsAuth extends \Tina4\Auth
{

    public function validToken(string $token, string $publicKey = "", string $encryption = \Nowakowskir\JWT\JWT::ALGORITHM_RS256): bool
    {
        if($token == $_ENV["API_TOKEN"]) {
            return true;
        } else {
            return parent::validToken($token, $publicKey, $encryption); // TODO: Change the autogenerated stub
        }
    }
}